version: '3.8'

services:
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/.
        init: true
        networks:
            - inception
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart: always
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/.
        init: true
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: always

    nginx:
        container_name: nginx
        build: ./requirements/nginx/.
        init: true
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
        restart: always
  

networks:
    inception:
        name: inception

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/${USER}/data/mariadb
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/${USER}/data/wordpress
            o: bind
            type: none