version: '3.8'
services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:433
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    env_file:
      - .env