version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - 443:433
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - wordpress:/var/lib/mysql
    restart: always
  wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/.
        init: true
        depends_on:
            - mariadb
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        restart: always
networks:
    inception:
        name: inception

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/ylarhris/data/mariadb
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/ylarhris/data/wordpress
            o: bind
            type: none